# Generated by Django 3.2 on 2021-05-14 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enterprise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del empleado')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido del empleado')),
                ('initiation_date', models.DateField(verbose_name='Fecha de iniciacion')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('document', models.CharField(max_length=255, verbose_name='Documento de identidad')),
                ('email', models.CharField(max_length=255, verbose_name='Correo electronico')),
                ('cellphone', models.CharField(max_length=15, verbose_name='Celular')),
                ('work_from_home', models.BooleanField(default=False, verbose_name='Trabajo desde la casa')),
                ('job_tittle', models.CharField(max_length=255, verbose_name='Nombre del cargo')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('eps', models.CharField(max_length=255, verbose_name='EPS')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='JobTittle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Nombre del empleado')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('files', models.BinaryField(verbose_name='Archivo')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
            ],
        ),
    ]
