# Generated by Django 3.2 on 2021-05-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employer_file_jobtittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='module',
            field=models.ManyToManyField(blank=True, related_name='enterprise_module', to='api.Module'),
        ),
    ]
