# Generated by Django 3.2 on 2021-06-03 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_enterprise_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtittle',
            name='cargo',
        ),
        migrations.AddField(
            model_name='jobtittle',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre del cargo'),
        ),
        migrations.CreateModel(
            name='TypeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Tipos de evaluacion')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de evaluacion',
                'verbose_name_plural': 'Tipos de evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Clase de evaluacion')),
                ('qualification', models.IntegerField(verbose_name='Calificacion')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('employee_evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_employer_evaluated', to='api.employer')),
                ('employee_evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_employer_evaluator', to='api.employer')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
    ]
