# Generated by Django 3.2 on 2021-06-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210603_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='feedback',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Retroalimentacion'),
        ),
    ]
