# Generated by Django 3.2 on 2021-06-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assessment_enterprise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='jobtittle',
            options={'verbose_name': 'Nombre del puesto', 'verbose_name_plural': 'Nombre de los puestos'},
        ),
    ]
